### ISSUE TITLE
USE flags?

### ISSUE THREAD

**Issue by voidcoefficient** [dumrich/moon#1]
I can't see if use use flags are an option. Are you planning on adding these?

**Comment by abhichavali** [comment]
Yes, absolutely. The actual MVP will take about another week to finish (So far, I have made it so that you can search for a package file and install it), but use flags are coming soon. As it is early, do you suggest using something like a make.conf, or a per package thing? Both?

**Comment by voidcoefficient** [comment]
I would do two files; one with global USE flags and one with all the flags for specific packages.
Portage makes a lot of files and I think it just it just makes too much of a mess
Ports uses just one file which I think it's good but after 100 flags you'd hope it was somewhere else

**Comment by voidcoefficient** [comment]
I may fork and PR something if you are okay with it? Small things. I'm doing the same thing as you, a [contained source-based distroless package manager](https://github.com/paulo-e/hydrogen) but it's not even installing things yet (because I'm doing a kernel, userspace, and shell too lol)

**Comment by abhichavali** [comment]
Yeah, that would actually be great. Honestly, I just finished the Rust book, so the code won't be the greatest, but if you're still interested, you can fork it. I am adding a contributing section to the README now...
